"use client";

import { ArrowLeft, Heart, Leaf, PackageOpen, ShoppingBag, Tag, Gavel, Trash2 } from "lucide-react";
import { useEffect,useState } from "react";

type Favorite={id:string;title:string;category:string;brand:string|null;size:string|null;dimensions:string|null;color:string|null;item_condition:string;sale_mode:"fixed"|"auction";price:number|null;starting_bid:number|null;image_urls:string[]};
const money=(value:number|null)=>Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function FavoritesPage(){
 const [items,setItems]=useState<Favorite[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[working,setWorking]=useState("");
 useEffect(()=>{fetch("/api/favorites").then(async response=>{const result=await response.json();if(response.status===401){window.location.href="/api/auth?returnTo=/perfil/favoritos";return}if(!response.ok)throw new Error(result.error);setItems(result.favorites)}).catch(reason=>setNotice(reason.message||"Não foi possível carregar seus favoritos.")).finally(()=>setLoading(false))},[]);
 async function remove(id:string){setWorking(id);const response=await fetch(`/api/favorites?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(response.ok){setItems(current=>current.filter(item=>item.id!==id));setNotice("Item removido dos favoritos.")}else{const result=await response.json();setNotice(result.error||"Não foi possível remover.")}setWorking("")}
 return <main className="favorites-page"><header className="wallet-header"><a className="brand" href="/"><span className="brand-cycle"><Leaf/></span><span>ViraVeste<small>Seu armário em movimento.</small></span></a><a href="/perfil"><ArrowLeft/> Voltar ao perfil</a></header><div className="favorites-shell"><section className="favorites-heading"><div><p className="eyebrow">Minha seleção</p><h1>Meus favoritos</h1><p>Os achados que você quer guardar para ver depois.</p></div><Heart/></section>{notice&&<p className="profile-notice">{notice}</p>}{loading?<div className="favorites-empty"><span className="spinner"/><p>Carregando favoritos...</p></div>:items.length===0?<div className="favorites-empty"><PackageOpen/><h2>Nenhum favorito ainda</h2><p>Toque no coração de um anúncio para encontrá-lo aqui.</p><a href="/buscar"><ShoppingBag/> Explorar catálogo</a></div>:<div className="favorites-grid">{items.map(item=><article key={item.id}><a className="favorite-product-image" href={`/produto/${item.id}`}><img src={item.image_urls[0]||"/images/editorial-verere.png"} alt={item.title}/><span>{item.item_condition}</span></a><div><p>{item.category}</p><h2><a href={`/produto/${item.id}`}>{item.title}</a></h2><small>{item.brand||"Sem marca"}{item.size?` · Tam. ${item.size}`:item.dimensions?` · ${item.dimensions}`:""}</small><strong>{item.sale_mode==="auction"?`Lance inicial: ${money(item.starting_bid)}`:money(item.price)}</strong><em>{item.sale_mode==="auction"?<><Gavel/> Leilão</>:<><Tag/> Preço fixo</>}</em></div><button disabled={working===item.id} onClick={()=>remove(item.id)} aria-label={`Remover ${item.title} dos favoritos`}><Trash2/> Remover</button></article>)}</div>}</div></main>;
}
