import { env } from "cloudflare:workers";

type Runtime={baseUrl:string;apiKey:string};
function config():Runtime|null{const runtime=env as unknown as Record<string,string|undefined>;return runtime.SUPABASE_URL&&runtime.SUPABASE_PUBLISHABLE_KEY?{baseUrl:runtime.SUPABASE_URL,apiKey:runtime.SUPABASE_PUBLISHABLE_KEY}:null}
function tokenFor(request:Request){const part=request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith("vv_access_token="));return part?decodeURIComponent(part.slice("vv_access_token=".length)):null}
function headers(apiKey:string,token:string,extra:Record<string,string>={}){return{apikey:apiKey,Authorization:`Bearer ${token}`,...extra}}
async function userId(runtime:Runtime,token:string){const response=await fetch(`${runtime.baseUrl}/auth/v1/user`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return null;return(await response.json() as {id:string}).id}
const valid=(id:string)=>/^[0-9a-f-]{36}$/i.test(id);
async function context(runtime:Runtime,token:string,user:string,conversation:Record<string,unknown>){const otherId=String(conversation.buyer_id===user?conversation.seller_id:conversation.buyer_id);const listingId=String(conversation.listing_id||"");const [profileResponse,listingResponse]=await Promise.all([fetch(`${runtime.baseUrl}/rest/v1/public_seller_profiles?select=id,display_name,city,state,avatar_url&id=eq.${encodeURIComponent(otherId)}`,{headers:headers(runtime.apiKey,token),cache:"no-store"}),listingId?fetch(`${runtime.baseUrl}/rest/v1/listings?select=id,title,image_urls,price,starting_bid,sale_mode&id=eq.${encodeURIComponent(listingId)}`,{headers:headers(runtime.apiKey,token),cache:"no-store"}):Promise.resolve(null)]);const profiles=profileResponse.ok?await profileResponse.json() as unknown[]:[];const listings=listingResponse?.ok?await listingResponse.json() as unknown[]:[];return{...conversation,other:profiles[0]||null,listing:listings[0]||null}}

export async function GET(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const token=tokenFor(request);if(!token)return Response.json({error:"Entre na sua conta para acessar as mensagens."},{status:401});const user=await userId(runtime,token);if(!user)return Response.json({error:"Sua sessão expirou."},{status:401});const id=new URL(request.url).searchParams.get("id")||"";const fields="id,buyer_id,seller_id,listing_id,created_at,updated_at";
 if(id){if(!valid(id))return Response.json({error:"Conversa inválida."},{status:400});const conversationResponse=await fetch(`${runtime.baseUrl}/rest/v1/conversations?select=${fields}&id=eq.${encodeURIComponent(id)}`,{headers:headers(runtime.apiKey,token),cache:"no-store"});const rows=conversationResponse.ok?await conversationResponse.json() as Array<Record<string,unknown>>:[];if(!rows.length)return Response.json({error:"Conversa não encontrada."},{status:404});const messagesResponse=await fetch(`${runtime.baseUrl}/rest/v1/messages?select=id,sender_id,body,created_at,read_at&conversation_id=eq.${encodeURIComponent(id)}&order=created_at.asc`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!messagesResponse.ok)return Response.json({error:"Não foi possível carregar as mensagens."},{status:messagesResponse.status});return Response.json({conversation:await context(runtime,token,user,rows[0]),messages:await messagesResponse.json(),currentUserId:user});}
 const response=await fetch(`${runtime.baseUrl}/rest/v1/conversations?select=${fields}&or=(buyer_id.eq.${user},seller_id.eq.${user})&order=updated_at.desc`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return Response.json({error:"Não foi possível carregar as conversas."},{status:response.status});const rows=await response.json() as Array<Record<string,unknown>>;const conversations=await Promise.all(rows.map(row=>context(runtime,token,user,row)));return Response.json({conversations,currentUserId:user});
}

export async function POST(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const token=tokenFor(request);if(!token)return Response.json({error:"Entre na sua conta para conversar."},{status:401});const user=await userId(runtime,token);if(!user)return Response.json({error:"Sua sessão expirou."},{status:401});const body=await request.json() as {sellerId?:string;listingId?:string;conversationId?:string;message?:string};
 if(body.conversationId){const conversationId=String(body.conversationId),message=String(body.message||"").trim().slice(0,2000);if(!valid(conversationId)||!message)return Response.json({error:"Escreva uma mensagem."},{status:400});const response=await fetch(`${runtime.baseUrl}/rest/v1/messages`,{method:"POST",headers:headers(runtime.apiKey,token,{"content-type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({conversation_id:conversationId,sender_id:user,body:message})});if(!response.ok)return Response.json({error:"Não foi possível enviar a mensagem."},{status:response.status});const rows=await response.json() as unknown[];return Response.json({message:rows[0]},{status:201});}
 const sellerId=String(body.sellerId||""),listingId=String(body.listingId||"");if(!valid(sellerId)||sellerId===user||(listingId&&!valid(listingId)))return Response.json({error:"Não é possível iniciar esta conversa."},{status:400});if(listingId){const listingResponse=await fetch(`${runtime.baseUrl}/rest/v1/listings?select=id&seller_id=eq.${encodeURIComponent(sellerId)}&id=eq.${encodeURIComponent(listingId)}&status=eq.published`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!listingResponse.ok||((await listingResponse.json()) as unknown[]).length===0)return Response.json({error:"O anúncio não está disponível."},{status:404});}
 const existingUrl=`${runtime.baseUrl}/rest/v1/conversations?select=id&buyer_id=eq.${user}&seller_id=eq.${encodeURIComponent(sellerId)}&${listingId?`listing_id=eq.${encodeURIComponent(listingId)}`:"listing_id=is.null"}`;const existingResponse=await fetch(existingUrl,{headers:headers(runtime.apiKey,token),cache:"no-store"});const existing=existingResponse.ok?await existingResponse.json() as Array<{id:string}>:[];if(existing.length)return Response.json({conversationId:existing[0].id});const response=await fetch(`${runtime.baseUrl}/rest/v1/conversations`,{method:"POST",headers:headers(runtime.apiKey,token,{"content-type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({buyer_id:user,seller_id:sellerId,listing_id:listingId||null})});if(!response.ok)return Response.json({error:"Não foi possível iniciar a conversa."},{status:response.status});const rows=await response.json() as Array<{id:string}>;return Response.json({conversationId:rows[0].id},{status:201});
}
