import { env } from "cloudflare:workers";

type Runtime={baseUrl:string;apiKey:string};
type Offer={id:string;listing_id:string;conversation_id:string;buyer_id:string;seller_id:string;created_by:string;parent_offer_id:string|null;amount:number;status:string;expires_at:string;created_at:string;responded_at:string|null};
function config():Runtime|null{const runtime=env as unknown as Record<string,string|undefined>;return runtime.SUPABASE_URL&&runtime.SUPABASE_PUBLISHABLE_KEY?{baseUrl:runtime.SUPABASE_URL,apiKey:runtime.SUPABASE_PUBLISHABLE_KEY}:null}
function tokenFor(request:Request){const part=request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith("vv_access_token="));return part?decodeURIComponent(part.slice("vv_access_token=".length)):null}
function headers(apiKey:string,token:string,extra:Record<string,string>={}){return{apikey:apiKey,Authorization:`Bearer ${token}`,...extra}}
async function userId(runtime:Runtime,token:string){const response=await fetch(`${runtime.baseUrl}/auth/v1/user`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return null;return(await response.json() as {id:string}).id}
const valid=(id:string)=>/^[0-9a-f-]{36}$/i.test(id);
const fields="id,listing_id,conversation_id,buyer_id,seller_id,created_by,parent_offer_id,amount,status,expires_at,created_at,responded_at";
async function setup(request:Request){const runtime=config();if(!runtime)return{error:Response.json({error:"Conexão não configurada."},{status:503})};const token=tokenFor(request);if(!token)return{error:Response.json({error:"Entre na sua conta para negociar."},{status:401})};const user=await userId(runtime,token);if(!user)return{error:Response.json({error:"Sua sessão expirou."},{status:401})};return{runtime,token,user};}

export async function GET(request:Request){
 const auth=await setup(request);if(auth.error)return auth.error;const {runtime,token}=auth;const params=new URL(request.url).searchParams;const conversation=params.get("conversation")||"",id=params.get("id")||"";if(!(valid(conversation)||valid(id)))return Response.json({error:"Negociação inválida."},{status:400});const filter=id?`id=eq.${encodeURIComponent(id)}`:`conversation_id=eq.${encodeURIComponent(conversation)}&order=created_at.asc`;const response=await fetch(`${runtime.baseUrl}/rest/v1/offers?select=${fields}&${filter}`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return Response.json({error:"Não foi possível carregar as propostas."},{status:response.status});const now=Date.now();const offers=(await response.json() as Offer[]).map(offer=>offer.status==="pending"&&new Date(offer.expires_at).getTime()<=now?{...offer,status:"expired"}:offer);return Response.json(id?{offer:offers[0]||null}:{offers});
}

export async function POST(request:Request){
 const auth=await setup(request);if(auth.error)return auth.error;const {runtime,token,user}=auth;const body=await request.json() as {listingId?:string;conversationId?:string;amount?:number;parentOfferId?:string};const listingId=String(body.listingId||""),conversationId=String(body.conversationId||""),parentId=body.parentOfferId?String(body.parentOfferId):null,amount=Number(body.amount);if(!valid(listingId)||!valid(conversationId)||!Number.isFinite(amount)||amount<=0||(parentId&&!valid(parentId)))return Response.json({error:"Confira o valor da proposta."},{status:400});
 const conversationResponse=await fetch(`${runtime.baseUrl}/rest/v1/conversations?select=id,buyer_id,seller_id,listing_id&id=eq.${conversationId}`,{headers:headers(runtime.apiKey,token),cache:"no-store"});const conversations=conversationResponse.ok?await conversationResponse.json() as Array<{buyer_id:string;seller_id:string;listing_id:string}>:[];const conversation=conversations[0];if(!conversation||conversation.listing_id!==listingId)return Response.json({error:"Esta conversa não corresponde ao anúncio."},{status:404});if(user!==conversation.buyer_id&&user!==conversation.seller_id)return Response.json({error:"Você não participa desta negociação."},{status:403});
 const listingResponse=await fetch(`${runtime.baseUrl}/rest/v1/listings?select=id,price,sale_mode,status&id=eq.${listingId}`,{headers:headers(runtime.apiKey,token),cache:"no-store"});const listings=listingResponse.ok?await listingResponse.json() as Array<{price:number|null;sale_mode:string;status:string}>:[];const listing=listings[0];if(!listing||listing.status!=="published"||listing.sale_mode!=="fixed")return Response.json({error:"Este anúncio não aceita propostas."},{status:400});
 if(!parentId){if(user!==conversation.buyer_id)return Response.json({error:"Somente o comprador pode iniciar uma proposta."},{status:403});if(listing.price!==null&&amount>=Number(listing.price))return Response.json({error:"Para esse valor, use a opção Comprar agora."},{status:400});}
 else{if(user!==conversation.seller_id)return Response.json({error:"Somente o vendedor pode enviar uma contraproposta."},{status:403});const parentResponse=await fetch(`${runtime.baseUrl}/rest/v1/offers?select=${fields}&id=eq.${parentId}&conversation_id=eq.${conversationId}`,{headers:headers(runtime.apiKey,token),cache:"no-store"});const parents=parentResponse.ok?await parentResponse.json() as Offer[]:[];const parent=parents[0];if(!parent||parent.status!=="pending"||new Date(parent.expires_at).getTime()<=Date.now())return Response.json({error:"A proposta original não está mais disponível."},{status:400});const update=await fetch(`${runtime.baseUrl}/rest/v1/offers?id=eq.${parentId}`,{method:"PATCH",headers:headers(runtime.apiKey,token,{"content-type":"application/json"}),body:JSON.stringify({status:"countered",responded_at:new Date().toISOString()})});if(!update.ok)return Response.json({error:"Não foi possível registrar a contraproposta."},{status:update.status});}
 const response=await fetch(`${runtime.baseUrl}/rest/v1/offers`,{method:"POST",headers:headers(runtime.apiKey,token,{"content-type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({listing_id:listingId,conversation_id:conversationId,buyer_id:conversation.buyer_id,seller_id:conversation.seller_id,created_by:user,parent_offer_id:parentId,amount:Number(amount.toFixed(2))})});if(!response.ok)return Response.json({error:"Não foi possível enviar a proposta."},{status:response.status});const rows=await response.json() as Offer[];return Response.json({offer:rows[0]},{status:201});
}

export async function PATCH(request:Request){
 const auth=await setup(request);if(auth.error)return auth.error;const {runtime,token,user}=auth;const body=await request.json() as {id?:string;status?:string};const id=String(body.id||""),status=String(body.status||"");if(!valid(id)||!["accepted","rejected","withdrawn"].includes(status))return Response.json({error:"Resposta inválida."},{status:400});const current=await fetch(`${runtime.baseUrl}/rest/v1/offers?select=${fields}&id=eq.${id}`,{headers:headers(runtime.apiKey,token),cache:"no-store"});const offers=current.ok?await current.json() as Offer[]:[];const offer=offers[0];if(!offer||offer.status!=="pending"||new Date(offer.expires_at).getTime()<=Date.now())return Response.json({error:"Esta proposta não está mais disponível."},{status:400});if(status==="withdrawn"&&user!==offer.buyer_id)return Response.json({error:"Apenas o comprador pode retirar a proposta."},{status:403});if(status!=="withdrawn"&&user!==offer.seller_id)return Response.json({error:"Apenas o vendedor pode responder à proposta."},{status:403});const response=await fetch(`${runtime.baseUrl}/rest/v1/offers?id=eq.${id}`,{method:"PATCH",headers:headers(runtime.apiKey,token,{"content-type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({status,responded_at:new Date().toISOString()})});if(!response.ok)return Response.json({error:"Não foi possível atualizar a proposta."},{status:response.status});const rows=await response.json() as Offer[];return Response.json({offer:rows[0]});
}
