import { env } from "cloudflare:workers";

type Runtime={baseUrl:string;apiKey:string};
function config():Runtime|null{const runtime=env as unknown as Record<string,string|undefined>;return runtime.SUPABASE_URL&&runtime.SUPABASE_PUBLISHABLE_KEY?{baseUrl:runtime.SUPABASE_URL,apiKey:runtime.SUPABASE_PUBLISHABLE_KEY}:null}
function tokenFor(request:Request){const part=request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith("vv_access_token="));return part?decodeURIComponent(part.slice("vv_access_token=".length)):null}
function headers(apiKey:string,token:string,extra:Record<string,string>={}){return{apikey:apiKey,Authorization:`Bearer ${token}`,...extra}}
async function userId(runtime:Runtime,token:string){const response=await fetch(`${runtime.baseUrl}/auth/v1/user`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return null;return(await response.json() as {id:string}).id}
function validId(id:string){return /^[0-9a-f-]{36}$/i.test(id)}

export async function GET(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const token=tokenFor(request);if(!token)return Response.json({error:"Entre na sua conta para ver os favoritos."},{status:401});const user=await userId(runtime,token);if(!user)return Response.json({error:"Sua sessão expirou."},{status:401});
 const id=new URL(request.url).searchParams.get("id")||"";const favoriteResponse=await fetch(`${runtime.baseUrl}/rest/v1/favorites?select=listing_id,created_at&user_id=eq.${user}${id?`&listing_id=eq.${encodeURIComponent(id)}`:""}&order=created_at.desc`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!favoriteResponse.ok)return Response.json({error:"Não foi possível carregar os favoritos."},{status:favoriteResponse.status});const favorites=await favoriteResponse.json() as Array<{listing_id:string;created_at:string}>;
 if(id)return Response.json({favorited:favorites.length>0});if(!favorites.length)return Response.json({favorites:[]});const ids=favorites.map(item=>item.listing_id);const encoded=`(${ids.join(",")})`;const fields="id,title,category,brand,size,dimensions,color,item_condition,sale_mode,price,starting_bid,image_urls,status";const listingResponse=await fetch(`${runtime.baseUrl}/rest/v1/listings?select=${fields}&id=in.${encodeURIComponent(encoded)}&status=eq.published`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!listingResponse.ok)return Response.json({error:"Não foi possível carregar os anúncios salvos."},{status:listingResponse.status});const listings=await listingResponse.json() as Array<{id:string}>;const order=new Map(ids.map((value,index)=>[value,index]));listings.sort((a,b)=>(order.get(a.id)??0)-(order.get(b.id)??0));return Response.json({favorites:listings});
}

export async function POST(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const token=tokenFor(request);if(!token)return Response.json({error:"Entre na sua conta para salvar favoritos."},{status:401});const user=await userId(runtime,token);if(!user)return Response.json({error:"Sua sessão expirou."},{status:401});const body=await request.json() as {listingId?:string};const listingId=String(body.listingId||"");if(!validId(listingId))return Response.json({error:"Anúncio inválido."},{status:400});const response=await fetch(`${runtime.baseUrl}/rest/v1/favorites`,{method:"POST",headers:headers(runtime.apiKey,token,{"content-type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify({user_id:user,listing_id:listingId})});if(!response.ok)return Response.json({error:"Não foi possível salvar o favorito."},{status:response.status});return Response.json({favorited:true});
}

export async function DELETE(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const token=tokenFor(request);if(!token)return Response.json({error:"Entre na sua conta."},{status:401});const user=await userId(runtime,token);if(!user)return Response.json({error:"Sua sessão expirou."},{status:401});const listingId=new URL(request.url).searchParams.get("id")||"";if(!validId(listingId))return Response.json({error:"Anúncio inválido."},{status:400});const response=await fetch(`${runtime.baseUrl}/rest/v1/favorites?user_id=eq.${user}&listing_id=eq.${encodeURIComponent(listingId)}`,{method:"DELETE",headers:headers(runtime.apiKey,token,{Prefer:"return=minimal"})});if(!response.ok)return Response.json({error:"Não foi possível remover o favorito."},{status:response.status});return Response.json({favorited:false});
}
