"use client";

import { ArrowLeft, Bell, ChevronRight, Clock3, FileCheck2, Gavel, Heart, Leaf, MessageCircle, PackageCheck, Plus, Search, ShieldCheck, Star, Tag, Truck } from "lucide-react";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { NotificationBell } from "@/components/notification-bell";

type Seller={id:string;display_name:string;city:string|null;state:string|null;avatar_url:string|null};
type Listing={id:string;seller_id:string;seller:Seller|null;title:string;description:string;category:string;brand:string|null;size:string|null;dimensions:string|null;color:string|null;item_condition:string;sale_mode:"fixed"|"auction";price:number|null;starting_bid:number|null;auction_ends_at:string|null;image_urls:string[];status:string;created_at:string};
const money=(value:number|null)=>`R$ ${Number(value??0).toFixed(2).replace(".",",")}`;

export default function RealProductPage(){
 const {id}=useParams<{id:string}>(); const [item,setItem]=useState<Listing|null>(null); const [photo,setPhoto]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState("");const [favorited,setFavorited]=useState(false);const [favoriteWorking,setFavoriteWorking]=useState(false);const [chatWorking,setChatWorking]=useState(false);const [offerOpen,setOfferOpen]=useState(false);const [offerAmount,setOfferAmount]=useState("");const [offerWorking,setOfferWorking]=useState(false);const [offerError,setOfferError]=useState("");
 useEffect(()=>{if(!id)return;fetch(`/api/listings?id=${encodeURIComponent(id)}`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setItem(result.listing)}).catch(error=>setError(error.message||"Não foi possível abrir este anúncio.")).finally(()=>setLoading(false));fetch(`/api/favorites?id=${encodeURIComponent(id)}`).then(response=>response.ok?response.json():Promise.reject()).then(result=>setFavorited(result.favorited)).catch(()=>{})},[id]);
 async function toggleFavorite(){setFavoriteWorking(true);const response=await fetch(favorited?`/api/favorites?id=${encodeURIComponent(id)}`:"/api/favorites",favorited?{method:"DELETE"}:{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({listingId:id})});if(response.status===401){window.location.href=`/api/auth?returnTo=/produto/${id}`;return}if(response.ok)setFavorited(current=>!current);setFavoriteWorking(false)}
 async function startConversation(){if(!item)return;setChatWorking(true);const response=await fetch("/api/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sellerId:item.seller_id,listingId:item.id})});const result=await response.json();if(response.status===401){window.location.href=`/api/auth?returnTo=/produto/${id}`;return}if(response.ok)window.location.href=`/perfil/mensagens/${result.conversationId}`;else{window.alert(result.error||"Não foi possível iniciar a conversa.");setChatWorking(false)}}
 async function makeOffer(event:React.FormEvent){event.preventDefault();if(!item)return;setOfferWorking(true);setOfferError("");const conversationResponse=await fetch("/api/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sellerId:item.seller_id,listingId:item.id})});const conversation=await conversationResponse.json();if(conversationResponse.status===401){window.location.href=`/api/auth?returnTo=/produto/${id}`;return}if(!conversationResponse.ok){setOfferError(conversation.error||"Não foi possível iniciar a negociação.");setOfferWorking(false);return}const response=await fetch("/api/offers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({listingId:item.id,conversationId:conversation.conversationId,amount:Number(offerAmount.replace(",","."))})});const result=await response.json();if(response.ok)window.location.href=`/perfil/mensagens/${conversation.conversationId}`;else{setOfferError(result.error||"Não foi possível enviar a proposta.");setOfferWorking(false)}}
 if(loading)return <main className="dynamic-product-state"><span className="spinner"/><p>Carregando anúncio...</p></main>;
 if(error||!item)return <main className="dynamic-product-state"><PackageCheck/><h1>Anúncio indisponível</h1><p>{error||"Este item não está mais disponível."}</p><a href="/buscar">Voltar ao catálogo</a></main>;
 const isAuction=item.sale_mode==="auction"; const images=item.image_urls.length?item.image_urls:["/images/editorial-verere.png"];const sellerName=item.seller?.display_name||"Vendedor ViraVeste";const sellerInitials=sellerName.split(" ").filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"VV";
 return <main><header className="topbar"><div className="topbar-inner"><a className="brand" href="/"><span className="brand-cycle"><Leaf/></span><span>ViraVeste<small>Seu armário em movimento.</small></span></a><form className="top-search" action="/buscar"><Search/><input name="q" aria-label="Buscar" placeholder="Buscar peças, marcas ou armários"/><button>Buscar</button></form><nav className="header-links"><a href="/buscar">Comprar</a><a href="/leiloes">Leilões</a></nav><div className="top-actions"><NotificationBell/><a className="login desktop-only" href="/entrar">Entrar</a><a className="sell desktop-only" href="/vender"><Plus/> Vender</a></div></div></header>
  <div className="product-page"><nav className="breadcrumb"><a href="/buscar"><ArrowLeft/> Voltar</a><span>Catálogo</span><ChevronRight/><span>{item.category}</span><ChevronRight/><strong>{item.title}</strong></nav>
   <section className="product-detail"><div className="product-gallery"><div className="product-main-photo"><img src={images[photo]} alt={`${item.title}, foto ${photo+1}`}/><button disabled={favoriteWorking} onClick={toggleFavorite} className={`detail-favorite ${favorited?"active":""}`} aria-label={favorited?"Remover anúncio dos favoritos":"Favoritar anúncio"}><Heart/> {favorited?"Salvo":"Salvar"}</button><span className="photo-count">{photo+1} / {images.length}</span></div>{images.length>1&&<div className="product-thumbs">{images.map((image,index)=><button className={photo===index?"active":""} onClick={()=>setPhoto(index)} key={image}><img src={image} alt={`Ver foto ${index+1}`}/></button>)}</div>}</div>
    <aside className="product-panel"><p className="detail-kicker">{item.brand||"Sem marca"}{item.size?` · Tamanho ${item.size}`:item.dimensions?` · ${item.dimensions}`:""}</p><h1>{item.title}</h1><div className="detail-state"><span>{item.item_condition}</span><small>Anúncio publicado</small></div><strong className="detail-price">{isAuction?money(item.starting_bid):money(item.price)}</strong><p className="installment">{isAuction?"Lance inicial do leilão":"Pagamento protegido pela plataforma"}</p><div className="detail-actions">{isAuction?<a className="buy-now" href={`/leiloes?produto=${item.id}`}><Gavel/> Participar do leilão</a>:<><a className="buy-now" href={`/checkout?produto=${item.id}`}>Comprar agora</a><button className="make-offer" onClick={()=>{setOfferAmount("");setOfferError("");setOfferOpen(true)}}>Fazer proposta</button></>}<button disabled={chatWorking} onClick={startConversation} className="talk-seller"><MessageCircle/> {chatWorking?"Abrindo conversa...":"Conversar com o vendedor"}</button></div>{isAuction&&<div className="dynamic-auction-note"><Clock3/><span><strong>Leilão ativo</strong><small>{item.auction_ends_at?`Encerramento previsto: ${new Date(item.auction_ends_at).toLocaleString("pt-BR")}`:"Confira as condições antes de ofertar."}</small></span></div>}<div className="shipping-box"><div><Truck/><span><strong>Calcule o frete</strong><small>Informe seu CEP para estimar a entrega.</small></span></div><form onSubmit={event=>event.preventDefault()}><input aria-label="CEP" placeholder="Digite seu CEP" inputMode="numeric"/><button>Calcular</button></form></div><div className="protection-note"><ShieldCheck/><span><strong>Compra protegida pela ViraVeste</strong><small>O valor só é liberado após o recebimento.</small></span></div></aside></section>
   <section className="product-information"><div className="description-card"><p className="eyebrow">Sobre o item</p><h2>Detalhes e conservação</h2><p>{item.description}</p><dl><div><dt>Categoria</dt><dd>{item.category}</dd></div><div><dt>Marca</dt><dd>{item.brand||"Não informada"}</dd></div><div><dt>Cor</dt><dd>{item.color||"Não informada"}</dd></div>{item.dimensions?<div><dt>Dimensões</dt><dd>{item.dimensions}</dd></div>:<div><dt>Tamanho</dt><dd>{item.size||"Não informado"}</dd></div>}<div><dt>Condição</dt><dd>{item.item_condition}</dd></div><div><dt>Modalidade</dt><dd>{isAuction?"Leilão":"Preço fixo"}</dd></div></dl></div><aside className="seller-card"><p className="eyebrow">Quem está vendendo</p><a className="seller-profile-link" href={`/armario/${item.seller_id}`}>{item.seller?.avatar_url?<img className="seller-avatar" src={item.seller.avatar_url} alt="Foto do vendedor"/>:<span className="seller-avatar">{sellerInitials}</span>}<div><h2>{sellerName}</h2><p>{[item.seller?.city,item.seller?.state].filter(Boolean).join(", ")||"Conta ViraVeste"}</p></div></a><div className="seller-rating"><Star/><strong>Novo</strong><span> · perfil protegido</span></div><ul><li><PackageCheck/> Anúncio publicado na plataforma</li><li><MessageCircle/> Converse antes de comprar, se precisar</li></ul><a href={`/armario/${item.seller_id}`}>Ver armário completo <ChevronRight/></a></aside></section>
   {item.category==="Peças de luxo"&&<div className="luxury-public-note"><FileCheck2/><span><strong>Documentação enviada para análise</strong><small>Os documentos permanecem privados e nunca são exibidos nesta página.</small></span></div>}
  </div><Dialog open={offerOpen} onOpenChange={setOfferOpen}><DialogContent className="offer-dialog"><DialogHeader><DialogTitle>Faça sua proposta</DialogTitle><DialogDescription>Envie um valor ao vendedor. A proposta fica válida por 48 horas.</DialogDescription></DialogHeader><form onSubmit={makeOffer}><label>Valor da proposta<span><b>R$</b><input autoFocus required min="0.01" max={Math.max(0.01,Number(item.price||0)-0.01)} step="0.01" inputMode="decimal" value={offerAmount} onChange={event=>setOfferAmount(event.target.value)} placeholder="0,00"/></span></label><small>Preço anunciado: {money(item.price)}</small>{offerError&&<p>{offerError}</p>}<button disabled={offerWorking||!offerAmount}>{offerWorking?"Enviando...":"Enviar proposta"}</button></form></DialogContent></Dialog><footer><div><a className="footer-brand" href="/">ViraVeste</a><p>Seu armário em movimento.</p></div><nav><a href="/politicas">Políticas</a><a href="/politicas#devolucoes">Devoluções</a><a href="/politicas#leiloes">Leilões</a></nav><span>© 2026 ViraVeste</span></footer>
 </main>
}
