"use client";

import { ArrowLeft, Eye, Gavel, Leaf, PackageOpen, Pause, Pencil, Play, Plus, Tag, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";

type Listing={id:string;title:string;category:string;brand:string|null;size:string|null;item_condition:string;sale_mode:"fixed"|"auction";price:number|null;starting_bid:number|null;auction_ends_at:string|null;image_urls:string[];status:"published"|"paused"|"reserved"|"sold"|"draft"|"rejected";created_at:string};
const statusLabel:Record<string,string>={published:"Publicado",paused:"Pausado",reserved:"Reservado",sold:"Vendido",draft:"Rascunho",rejected:"Em análise"};

export default function MyListingsPage(){
 const [listings,setListings]=useState<Listing[]>([]); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(""); const [working,setWorking]=useState("");
 async function load(){setLoading(true);const response=await fetch("/api/listings?mine=1");if(response.status===401){window.location.href="/api/auth?returnTo=/perfil/anuncios";return}const result=await response.json();if(response.ok)setListings(result.listings);else setNotice(result.error||"Não foi possível carregar seus anúncios.");setLoading(false)}
 useEffect(()=>{load()},[]);
 async function changeStatus(item:Listing){const next=item.status==="paused"?"published":"paused";setWorking(item.id);setNotice("");const response=await fetch("/api/listings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,status:next})});const result=await response.json();if(response.ok){setListings(current=>current.map(listing=>listing.id===item.id?{...listing,status:next}:listing));setNotice(next==="paused"?"Anúncio pausado.":"Anúncio reativado.")}else setNotice(result.error||"Não foi possível alterar o anúncio.");setWorking("")}
 async function remove(item:Listing){if(!window.confirm(`Excluir “${item.title}”? Essa ação não poderá ser desfeita.`))return;setWorking(item.id);setNotice("");const response=await fetch(`/api/listings?id=${encodeURIComponent(item.id)}`,{method:"DELETE"});const result=await response.json();if(response.ok){setListings(current=>current.filter(listing=>listing.id!==item.id));setNotice("Anúncio excluído.")}else setNotice(result.error||"Não foi possível excluir o anúncio.");setWorking("")}
 return <main className="my-listings-page"><header className="wallet-header"><a className="brand" href="/"><span className="brand-cycle"><Leaf/></span><span>ViraVeste<small>Seu armário em movimento.</small></span></a><a href="/perfil"><ArrowLeft/> Voltar ao perfil</a></header><div className="my-listings-shell"><section className="my-listings-heading"><div><p className="eyebrow">Meu armário</p><h1>Meus anúncios</h1><p>Acompanhe o que está à venda e controle a visibilidade de cada item.</p></div><a href="/vender"><Plus/> Novo anúncio</a></section>{notice&&<p className="profile-notice">{notice}</p>}{loading?<div className="listings-empty"><span className="spinner"/><p>Carregando seus anúncios...</p></div>:listings.length===0?<div className="listings-empty"><PackageOpen/><h2>Seu armário está vazio</h2><p>Publique uma peça para começar.</p><a href="/vender">Criar anúncio</a></div>:<div className="my-listings-grid">{listings.map(item=><article key={item.id}><div className="my-listing-image"><img src={item.image_urls[0]||"/images/editorial-verere.png"} alt={item.title}/><span className={`listing-status ${item.status}`}>{statusLabel[item.status]||item.status}</span></div><div className="my-listing-copy"><p>{item.category}{item.brand?` · ${item.brand}`:""}</p><h2>{item.title}</h2><span>{item.item_condition}{item.size?` · Tam. ${item.size}`:""}</span><strong>{item.sale_mode==="auction"?`Lance inicial: R$ ${Number(item.starting_bid).toFixed(2).replace(".",",")}`:`R$ ${Number(item.price).toFixed(2).replace(".",",")}`}</strong><small>{item.sale_mode==="auction"?<><Gavel/> Leilão</>:<><Tag/> Preço fixo</>}</small></div><nav><a href={`/produto/${item.id}`}><Eye/> Ver anúncio</a>{["published","paused","draft"].includes(item.status)&&<a href={`/perfil/anuncios/${item.id}/editar`}><Pencil/> Editar</a>}{["published","paused"].includes(item.status)&&<button disabled={working===item.id} onClick={()=>changeStatus(item)}>{item.status==="paused"?<><Play/> Reativar</>:<><Pause/> Pausar</>}</button>}<button className="delete" disabled={working===item.id} onClick={()=>remove(item)}><Trash2/> Excluir</button></nav></article>)}</div>}</div></main>
}
