import { env } from "cloudflare:workers";

type Runtime={baseUrl:string;apiKey:string};
function config():Runtime|null{const runtime=env as unknown as Record<string,string|undefined>;return runtime.SUPABASE_URL&&runtime.SUPABASE_PUBLISHABLE_KEY?{baseUrl:runtime.SUPABASE_URL,apiKey:runtime.SUPABASE_PUBLISHABLE_KEY}:null}
function tokenFor(request:Request){const part=request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith("vv_access_token="));return part?decodeURIComponent(part.slice("vv_access_token=".length)):null}
function headers(apiKey:string,token?:string,extra:Record<string,string>={}){return{apikey:apiKey,Authorization:`Bearer ${token||apiKey}`,...extra}}
async function userId(runtime:Runtime,token:string){const response=await fetch(`${runtime.baseUrl}/auth/v1/user`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return null;return(await response.json() as {id:string}).id}
const valid=(id:string)=>/^[0-9a-f-]{36}$/i.test(id);

export async function GET(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const sellerId=new URL(request.url).searchParams.get("seller")||"";const token=tokenFor(request);let user:string|null=null;if(token)user=await userId(runtime,token);
 if(sellerId){if(!valid(sellerId))return Response.json({error:"Vendedor inválido."},{status:400});const countResponse=await fetch(`${runtime.baseUrl}/rest/v1/rpc/seller_follower_count`,{method:"POST",headers:headers(runtime.apiKey,token||undefined,{"content-type":"application/json"}),body:JSON.stringify({target_seller_id:sellerId})});const followers=countResponse.ok?Number(await countResponse.json()):0;let following=false;if(user){const response=await fetch(`${runtime.baseUrl}/rest/v1/seller_follows?select=seller_id&follower_id=eq.${user}&seller_id=eq.${encodeURIComponent(sellerId)}`,{headers:headers(runtime.apiKey,token!),cache:"no-store"});if(response.ok)following=((await response.json()) as unknown[]).length>0}return Response.json({following,followers,isOwn:user===sellerId});}
 if(!token||!user)return Response.json({error:"Entre na sua conta para ver os armários seguidos."},{status:401});const followsResponse=await fetch(`${runtime.baseUrl}/rest/v1/seller_follows?select=seller_id,created_at&follower_id=eq.${user}&order=created_at.desc`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!followsResponse.ok)return Response.json({error:"Não foi possível carregar os armários seguidos."},{status:followsResponse.status});const follows=await followsResponse.json() as Array<{seller_id:string}>;if(!follows.length)return Response.json({sellers:[]});const ids=follows.map(item=>item.seller_id),inFilter=`(${ids.join(",")})`;const profilesResponse=await fetch(`${runtime.baseUrl}/rest/v1/public_seller_profiles?select=id,display_name,city,state,avatar_url,member_since,bio&id=in.${encodeURIComponent(inFilter)}`,{headers:headers(runtime.apiKey),cache:"no-store"});if(!profilesResponse.ok)return Response.json({error:"Não foi possível carregar os vendedores."},{status:profilesResponse.status});const sellers=await profilesResponse.json() as Array<{id:string}>;const order=new Map(ids.map((id,index)=>[id,index]));sellers.sort((a,b)=>(order.get(a.id)??0)-(order.get(b.id)??0));return Response.json({sellers});
}

export async function POST(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const token=tokenFor(request);if(!token)return Response.json({error:"Entre na sua conta para seguir este armário."},{status:401});const user=await userId(runtime,token);if(!user)return Response.json({error:"Sua sessão expirou."},{status:401});const body=await request.json() as {sellerId?:string};const sellerId=String(body.sellerId||"");if(!valid(sellerId)||sellerId===user)return Response.json({error:"Não é possível seguir este armário."},{status:400});const response=await fetch(`${runtime.baseUrl}/rest/v1/seller_follows`,{method:"POST",headers:headers(runtime.apiKey,token,{"content-type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify({follower_id:user,seller_id:sellerId})});if(!response.ok)return Response.json({error:"Não foi possível seguir agora."},{status:response.status});return Response.json({following:true});
}

export async function DELETE(request:Request){
 const runtime=config();if(!runtime)return Response.json({error:"Conexão não configurada."},{status:503});const token=tokenFor(request);if(!token)return Response.json({error:"Entre na sua conta."},{status:401});const user=await userId(runtime,token);if(!user)return Response.json({error:"Sua sessão expirou."},{status:401});const sellerId=new URL(request.url).searchParams.get("seller")||"";if(!valid(sellerId))return Response.json({error:"Vendedor inválido."},{status:400});const response=await fetch(`${runtime.baseUrl}/rest/v1/seller_follows?follower_id=eq.${user}&seller_id=eq.${encodeURIComponent(sellerId)}`,{method:"DELETE",headers:headers(runtime.apiKey,token,{Prefer:"return=minimal"})});if(!response.ok)return Response.json({error:"Não foi possível deixar de seguir."},{status:response.status});return Response.json({following:false});
}
