import { env } from "cloudflare:workers";
type Runtime={baseUrl:string;apiKey:string};
function config():Runtime|null{const r=env as unknown as Record<string,string|undefined>;return r.SUPABASE_URL&&r.SUPABASE_PUBLISHABLE_KEY?{baseUrl:r.SUPABASE_URL,apiKey:r.SUPABASE_PUBLISHABLE_KEY}:null}
function tokenFor(request:Request){const p=request.headers.get("cookie")?.split(";").map(v=>v.trim()).find(v=>v.startsWith("vv_access_token="));return p?decodeURIComponent(p.slice("vv_access_token=".length)):null}
function headers(key:string,token:string,extra:Record<string,string>={}){return{apikey:key,Authorization:"Bearer "+token,...extra}}
async function userId(r:Runtime,t:string){const x=await fetch(r.baseUrl+"/auth/v1/user",{headers:headers(r.apiKey,t),cache:"no-store"});return x.ok?(await x.json() as {id:string}).id:null}
const valid=(id:string)=>/^[0-9a-f-]{36}$/i.test(id);
async function setup(request:Request){const runtime=config();if(!runtime)return{error:Response.json({error:"Conexão não configurada."},{status:503})};const token=tokenFor(request);if(!token)return{error:Response.json({error:"Entre na sua conta."},{status:401})};const user=await userId(runtime,token);if(!user)return{error:Response.json({error:"Sua sessão expirou."},{status:401})};return{runtime,token,user}}
export async function GET(request:Request){const auth=await setup(request);if(auth.error)return auth.error;const {runtime,token}=auth;const countOnly=new URL(request.url).searchParams.get("count")==="1",select=countOnly?"id":"id,notification_type,title,body,link,read_at,created_at",suffix=countOnly?"&read_at=is.null":"&order=created_at.desc&limit=100";const response=await fetch(runtime.baseUrl+"/rest/v1/notifications?select="+select+suffix,{headers:headers(runtime.apiKey,token,countOnly?{Prefer:"count=exact"}:{}),cache:"no-store"});if(!response.ok)return Response.json({error:"Não foi possível carregar as notificações."},{status:response.status});if(countOnly){const range=response.headers.get("content-range")||"0/0",total=Number(range.split("/")[1]||0);return Response.json({unread:total})}const notifications=await response.json() as Array<{read_at:string|null}>;return Response.json({notifications,unread:notifications.filter(item=>!item.read_at).length})}
export async function PATCH(request:Request){const auth=await setup(request);if(auth.error)return auth.error;const {runtime,token}=auth;const body=await request.json() as {id?:string;all?:boolean};if(!body.all&&!valid(String(body.id||"")))return Response.json({error:"Notificação inválida."},{status:400});const filter=body.all?"read_at=is.null":"id=eq."+encodeURIComponent(String(body.id));const response=await fetch(runtime.baseUrl+"/rest/v1/notifications?"+filter,{method:"PATCH",headers:headers(runtime.apiKey,token,{"content-type":"application/json"}),body:JSON.stringify({read_at:new Date().toISOString()})});if(!response.ok)return Response.json({error:"Não foi possível atualizar a notificação."},{status:response.status});return Response.json({success:true})}
