"use client";

import { Heart, Leaf, MessageCircle, Search, SlidersHorizontal, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

const categories=["Todas","Novidades","Roupas","Bolsas","Calçados","Acessórios","Luxo","Objetos","Casa, mesa e banho","Antiguidades","Outros"];
type Product={id:string|null;seller:string;city:string;avatar:string;tone:string;name:string;brand:string;size:string;state:string;category:string;price:number;likes:number;image:string;href:string};
const products:Product[]=[
 {id:null,seller:"Camila R.",city:"Rio Verde, GO",avatar:"CA",tone:"#f05a47",name:"Vestido midi de linho",brand:"Amissima",size:"M",state:"Excelente",category:"Roupas",price:189,likes:24,image:"/images/vestido-terracota.png",href:"/produto/vestido-midi-linho"},
 {id:null,seller:"Marina Lopes",city:"Goiânia, GO",avatar:"MA",tone:"#4d7c6b",name:"Bolsa hobo oliva",brand:"Couro & Co.",size:"Único",state:"Como nova",category:"Bolsas",price:245,likes:41,image:"/images/bolsa-sapato.png",href:"#"},
 {id:null,seller:"Luiza Freitas",city:"Brasília, DF",avatar:"LU",tone:"#d9a928",name:"Slingback em couro areia",brand:"Arezzo",size:"37",state:"Bom estado",category:"Calçados",price:159,likes:18,image:"/images/bolsa-sapato.png",href:"#"},
 {id:null,seller:"Ana Clara",city:"Rio Verde, GO",avatar:"AC",tone:"#294c73",name:"Conjunto em tons naturais",brand:"Mixed",size:"P",state:"Excelente",category:"Roupas",price:320,likes:33,image:"/images/editorial-verere.png",href:"#"},
 {id:null,seller:"Beatriz M.",city:"Uberlândia, MG",avatar:"BE",tone:"#a94d65",name:"Vestido terracota",brand:"Ateliê local",size:"G",state:"Muito bom",category:"Roupas",price:145,likes:12,image:"/images/vestido-terracota.png",href:"#"},
 {id:null,seller:"Sofia Nunes",city:"São Paulo, SP",avatar:"SO",tone:"#2d7d79",name:"Bolsa oliva minimalista",brand:"Vintage",size:"Único",state:"Bom estado",category:"Antiguidades",price:198,likes:29,image:"/images/bolsa-sapato.png",href:"#"},
 {id:null,seller:"Camila R.",city:"Rio Verde, GO",avatar:"CA",tone:"#f05a47",name:"Colete de linho natural",brand:"Farm",size:"M",state:"Como novo",category:"Roupas",price:129,likes:16,image:"/images/editorial-verere.png",href:"#"},
 {id:null,seller:"Marina Lopes",city:"Goiânia, GO",avatar:"MA",tone:"#4d7c6b",name:"Scarpin areia clássico",brand:"Schutz",size:"36",state:"Excelente",category:"Luxo",price:210,likes:27,image:"/images/bolsa-sapato.png",href:"#"},
];
function Avatar({initials,tone}:{initials:string;tone:string}){return <span className="avatar" style={{background:tone}}>{initials}</span>}
const normal=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
function catalogCategory(value:string){if(["Vestidos","Blusas","Calças","Casacos"].includes(value))return "Roupas";if(value==="Peças de luxo")return "Luxo";if(["Objetos e decoração","Móveis","Livros","Arte e artesanato"].includes(value))return "Objetos";if(value==="Casa, mesa e banho")return "Casa, mesa e banho";if(value==="Antiguidades e colecionáveis")return "Antiguidades";return value}

export default function SearchPage(){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("Todas"); const [condition,setCondition]=useState("Todos"); const [maxPrice,setMaxPrice]=useState(500); const [order,setOrder]=useState("relevantes"); const [liveProducts,setLiveProducts]=useState<Product[]>([]);const [favorites,setFavorites]=useState<Set<string>>(new Set());const [favoriteWorking,setFavoriteWorking]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setQuery(p.get("q")||"");setCategory(p.get("categoria")||"Todas");setOrder(p.get("ordem")||"relevantes");fetch("/api/listings").then(response=>response.ok?response.json():Promise.reject()).then(({listings})=>setLiveProducts(listings.map((item:{id:string;title:string;brand:string|null;size:string|null;item_condition:string;category:string;price:number|null;starting_bid:number|null;image_urls:string[];seller?:{display_name?:string;city?:string;state?:string}|null})=>{const sellerName=item.seller?.display_name||"Vendedor ViraVeste";return{id:item.id,seller:sellerName,city:[item.seller?.city,item.seller?.state].filter(Boolean).join(", ")||"Brasil",avatar:sellerName.split(" ").filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"VV",tone:"#173f35",name:item.title,brand:item.brand||"Sem marca",size:item.size||"Único",state:item.item_condition,category:catalogCategory(item.category),price:Number(item.price??item.starting_bid??0),likes:0,image:item.image_urls[0]||"/images/editorial-verere.png",href:`/produto/${item.id}`}}))).catch(()=>{});fetch("/api/favorites").then(response=>response.ok?response.json():Promise.reject()).then(({favorites:items})=>setFavorites(new Set(items.map((item:{id:string})=>item.id)))).catch(()=>{})},[]);
 async function toggleFavorite(product:Product){if(!product.id)return;setFavoriteWorking(product.id);const active=favorites.has(product.id);const response=await fetch(active?`/api/favorites?id=${encodeURIComponent(product.id)}`:"/api/favorites",active?{method:"DELETE"}:{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({listingId:product.id})});if(response.status===401){window.location.href=`/api/auth?returnTo=${encodeURIComponent(window.location.pathname+window.location.search)}`;return}if(response.ok)setFavorites(current=>{const next=new Set(current);active?next.delete(product.id!):next.add(product.id!);return next});setFavoriteWorking("")}
 const availableProducts=liveProducts.length?liveProducts:products;
 const results=useMemo(()=>availableProducts.filter(p=>{const text=normal(`${p.name} ${p.brand} ${p.seller} ${p.category}`);return (!query||text.includes(normal(query)))&&(category==="Todas"||category==="Novidades"||p.category===category)&&(condition==="Todos"||p.state===condition)&&p.price<=maxPrice}).sort((a,b)=>order==="menor"?a.price-b.price:order==="maior"?b.price-a.price:0),[availableProducts,query,category,condition,maxPrice,order]);
 function submit(e:FormEvent){e.preventDefault();const p=new URLSearchParams();if(query)p.set("q",query);if(category!=="Todas")p.set("categoria",category);window.history.replaceState(null,"",`/buscar?${p}`)}
 function clear(){setQuery("");setCategory("Todas");setCondition("Todos");setMaxPrice(500);setOrder("relevantes");window.history.replaceState(null,"","/buscar")}
 return <main><header className="topbar"><div className="topbar-inner search-header"><a className="brand" href="/"><span className="brand-cycle"><Leaf/></span><span>ViraVeste<small>Seu armário em movimento.</small></span></a><form className="top-search" onSubmit={submit}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Buscar" placeholder="Buscar peças, marcas ou armários"/><button type="submit">Buscar</button></form><a className="login desktop-only" href="/entrar">Entrar</a><a className="sell desktop-only" href="/vender">Vender</a></div></header>
  <nav className="category-nav" aria-label="Categorias"><div>{categories.slice(1).map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></nav>
  <div className="catalog-shell"><aside className="catalog-filters"><div className="filter-title"><SlidersHorizontal/><strong>Filtros</strong><button onClick={clear}>Limpar</button></div><fieldset><legend>Categoria</legend><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></fieldset><fieldset><legend>Estado de conservação</legend>{["Todos","Excelente","Como nova","Como novo","Muito bom","Bom estado"].map(c=><label key={c}><input type="radio" name="condition" checked={condition===c} onChange={()=>setCondition(c)}/>{c}</label>)}</fieldset><fieldset><legend>Preço máximo</legend><input type="range" min="50" max="500" step="10" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/><div className="price-range"><span>R$ 50</span><strong>até R$ {maxPrice}</strong></div></fieldset></aside>
   <section className="catalog-results"><div className="catalog-heading"><div><p className="eyebrow">Garimpo ViraVeste</p><h1>{query?`Resultados para “${query}”`:category!=="Todas"?category:"Todos os achados"}</h1><p>{results.length} {results.length===1?"item encontrado":"itens encontrados"}</p></div><label>Ordenar por<select value={order} onChange={e=>setOrder(e.target.value)}><option value="relevantes">Mais relevantes</option><option value="recentes">Mais recentes</option><option value="menor">Menor preço</option><option value="maior">Maior preço</option></select></label></div>
    {(query||category!=="Todas"||condition!=="Todos"||maxPrice<500)&&<div className="active-filters"><span>Filtros ativos</span><button onClick={clear}><X/> Limpar tudo</button></div>}
    {results.length?<div className="product-grid catalog-grid">{results.map((p,index)=><article className="product-card" key={p.seller+p.name}><div className="product-image"><a href={p.href}><img className={`crop crop-${index}`} src={p.image} alt={p.name}/></a>{p.id&&<button className={`favorite ${favorites.has(p.id)?"active":""}`} disabled={favoriteWorking===p.id} onClick={()=>toggleFavorite(p)} type="button" aria-label={`${favorites.has(p.id)?"Remover":"Adicionar"} ${p.name} dos favoritos`}><Heart/><span>{favorites.has(p.id)?"Salvo":"Salvar"}</span></button>}<span className="condition">{p.state}</span></div><div className="product-copy"><p>{p.brand} · Tam. {p.size}</p><h3>{p.name}</h3><strong>R$ {p.price}</strong></div><div className="seller-line"><Avatar initials={p.avatar} tone={p.tone}/><div><strong>{p.seller}</strong><span>{p.city}</span></div><button aria-label="Conversar"><MessageCircle/></button></div></article>)}</div>:<div className="catalog-empty"><Search/><h2>Nenhum achado por aqui</h2><p>Tente outro termo ou retire alguns filtros.</p><button onClick={clear}>Limpar busca</button></div>}
    <small className="catalog-demo">Catálogo demonstrativo para validar a experiência. Os anúncios reais serão ligados ao banco de dados na próxima etapa.</small></section></div>
 </main>
}
