create table if not exists public.seller_follows (follower_id uuid not null references auth.users(id) on delete cascade,seller_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key (follower_id,seller_id),constraint seller_follows_cannot_follow_self check (follower_id <> seller_id));
create index if not exists seller_follows_seller_id_idx on public.seller_follows(seller_id);
alter table public.seller_follows enable row level security;
drop policy if exists "Users can view own follows" on public.seller_follows;
create policy "Users can view own follows" on public.seller_follows for select to authenticated using (auth.uid()=follower_id);
drop policy if exists "Users can follow sellers" on public.seller_follows;
create policy "Users can follow sellers" on public.seller_follows for insert to authenticated with check (auth.uid()=follower_id);
drop policy if exists "Users can unfollow sellers" on public.seller_follows;
create policy "Users can unfollow sellers" on public.seller_follows for delete to authenticated using (auth.uid()=follower_id);
grant select,insert,delete on public.seller_follows to authenticated;
create or replace function public.seller_follower_count(target_seller_id uuid) returns bigint language sql stable security definer set search_path='' as $$ select count(*) from public.seller_follows where seller_id=target_seller_id; $$;
revoke all on function public.seller_follower_count(uuid) from public;
grant execute on function public.seller_follower_count(uuid) to anon,authenticated;
alter table public.profiles add column if not exists bio text;
alter table public.profiles drop constraint if exists profiles_bio_length;
alter table public.profiles add constraint profiles_bio_length check (bio is null or char_length(bio)<=500);
create or replace view public.public_seller_profiles with (security_barrier=true) as select id,coalesce(nullif(trim(full_name),''),'Vendedor ViraVeste') as display_name,city,state,avatar_url,created_at as member_since,bio from public.profiles where account_status='active';
revoke all on public.public_seller_profiles from public,anon,authenticated;
grant select on public.public_seller_profiles to anon,authenticated;
