-- Histórico e contestações (executado no SQL Editor).
create table if not exists public.order_events(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,actor_id uuid references auth.users(id),event_type text not null check(event_type in ('order_created','payment_confirmed','shipment_prepared','shipped','delivered','completed','cancellation_requested','cancelled','issue_opened')),description text,created_at timestamptz not null default now());
create table if not exists public.order_issues(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,opened_by uuid not null references auth.users(id),reason text not null check(reason in ('delivery_delay','damaged_item','different_item','counterfeit_suspicion','missing_item','other')),description text not null check(char_length(description) between 10 and 2000),status text not null default 'open' check(status in ('open','under_review','resolved_buyer','resolved_seller','closed')),created_at timestamptz not null default now(),resolved_at timestamptz);
create index if not exists order_events_order_id_idx on public.order_events(order_id,created_at);create index if not exists order_issues_order_id_idx on public.order_issues(order_id,created_at);alter table public.order_events enable row level security;alter table public.order_issues enable row level security;
create policy "Participantes visualizam histórico" on public.order_events for select using(exists(select 1 from public.orders where orders.id=order_events.order_id and (orders.buyer_id=auth.uid() or orders.seller_id=auth.uid())));create policy "Participantes visualizam problemas" on public.order_issues for select using(exists(select 1 from public.orders where orders.id=order_issues.order_id and (orders.buyer_id=auth.uid() or orders.seller_id=auth.uid())));create policy "Comprador abre contestação" on public.order_issues for insert with check(opened_by=auth.uid() and exists(select 1 from public.orders where orders.id=order_issues.order_id and orders.buyer_id=auth.uid()));create policy "Participantes atualizam acompanhamento" on public.orders for update using(auth.uid()=buyer_id or auth.uid()=seller_id) with check(auth.uid()=buyer_id or auth.uid()=seller_id);grant select on public.order_events to authenticated;grant select,insert on public.order_issues to authenticated;grant update(order_status,tracking_code,shipped_at,delivered_at,cancelled_at) on public.orders to authenticated;
create or replace function public.protect_order_update() returns trigger language plpgsql security invoker set search_path=public as $$ begin
if new.id<>old.id or new.listing_id<>old.listing_id or new.offer_id is distinct from old.offer_id or new.buyer_id<>old.buyer_id or new.seller_id<>old.seller_id or new.sale_mode<>old.sale_mode or new.item_price<>old.item_price or new.protection_fee<>old.protection_fee or new.shipping_price<>old.shipping_price or new.total_amount<>old.total_amount or new.payment_status<>old.payment_status or new.payment_method is distinct from old.payment_method or new.shipping_method is distinct from old.shipping_method or new.recipient_name<>old.recipient_name or new.postal_code<>old.postal_code or new.street<>old.street or new.address_number<>old.address_number or new.complement is distinct from old.complement or new.neighborhood<>old.neighborhood or new.city<>old.city or new.state<>old.state or new.created_at<>old.created_at then raise exception 'Os dados principais do pedido não podem ser alterados';end if;
if auth.uid()=old.seller_id then if new.delivered_at is distinct from old.delivered_at or new.cancelled_at is distinct from old.cancelled_at then raise exception 'O vendedor não pode alterar estes dados';end if;if new.order_status='preparing_shipment' and old.order_status='payment_confirmed' then null;elsif new.order_status='shipped' and old.order_status in ('payment_confirmed','preparing_shipment') then if old.payment_status<>'paid' then raise exception 'O pagamento ainda não foi confirmado';end if;if new.tracking_code is null or char_length(trim(new.tracking_code))<5 then raise exception 'Informe um código de rastreamento válido';end if;new.shipped_at=now();elsif new.order_status<>old.order_status then raise exception 'O vendedor não pode realizar esta alteração';end if;
elsif auth.uid()=old.buyer_id then if new.tracking_code is distinct from old.tracking_code or new.shipped_at is distinct from old.shipped_at then raise exception 'O comprador não pode alterar os dados de envio';end if;if new.order_status='delivered' and old.order_status='shipped' then new.delivered_at=now();elsif new.order_status='cancellation_requested' and old.order_status in ('awaiting_payment','payment_confirmed','preparing_shipment') then null;elsif new.order_status='disputed' and old.order_status in ('payment_confirmed','preparing_shipment','shipped','delivered') then null;elsif new.order_status<>old.order_status then raise exception 'O comprador não pode realizar esta alteração';end if;else raise exception 'Usuário não autorizado';end if;return new;end;$$;
drop trigger if exists protect_order_update_trigger on public.orders;create trigger protect_order_update_trigger before update on public.orders for each row execute function public.protect_order_update();
create or replace function public.register_order_event() returns trigger language plpgsql security definer set search_path=public as $$ declare event_name text;begin if tg_op='INSERT' then event_name:='order_created';elsif new.order_status is distinct from old.order_status then event_name:=case new.order_status when 'payment_confirmed' then 'payment_confirmed' when 'preparing_shipment' then 'shipment_prepared' when 'shipped' then 'shipped' when 'delivered' then 'delivered' when 'completed' then 'completed' when 'cancellation_requested' then 'cancellation_requested' when 'cancelled' then 'cancelled' when 'disputed' then 'issue_opened' else null end;end if;if event_name is not null then insert into public.order_events(order_id,actor_id,event_type) values(new.id,auth.uid(),event_name);end if;return new;end;$$;
drop trigger if exists register_order_event_trigger on public.orders;create trigger register_order_event_trigger after insert or update on public.orders for each row execute function public.register_order_event();
