"use client";

import { ArrowLeft, Leaf, MapPin, Store, UserMinus } from "lucide-react";
import { useEffect,useState } from "react";
type Seller={id:string;display_name:string;city:string|null;state:string|null;avatar_url:string|null;bio:string|null};
const initials=(name:string)=>name.split(" ").filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"VV";
export default function FollowingPage(){
 const [sellers,setSellers]=useState<Seller[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[working,setWorking]=useState("");
 useEffect(()=>{fetch("/api/follows").then(async response=>{const result=await response.json();if(response.status===401){window.location.href="/api/auth?returnTo=/perfil/seguindo";return}if(!response.ok)throw new Error(result.error);setSellers(result.sellers)}).catch(reason=>setNotice(reason.message||"Não foi possível carregar os armários.")).finally(()=>setLoading(false))},[]);
 async function unfollow(id:string){setWorking(id);const response=await fetch(`/api/follows?seller=${encodeURIComponent(id)}`,{method:"DELETE"});if(response.ok){setSellers(current=>current.filter(item=>item.id!==id));setNotice("Você deixou de seguir este armário.")}else{const result=await response.json();setNotice(result.error||"Não foi possível alterar.")}setWorking("")}
 return <main className="following-page"><header className="wallet-header"><a className="brand" href="/"><span className="brand-cycle"><Leaf/></span><span>ViraVeste<small>Seu armário em movimento.</small></span></a><a href="/perfil"><ArrowLeft/> Voltar ao perfil</a></header><div className="following-shell"><section className="following-heading"><p className="eyebrow">Minha rede</p><h1>Armários que sigo</h1><p>Acompanhe vendedores e encontre novamente as seleções que você gostou.</p></section>{notice&&<p className="profile-notice">{notice}</p>}{loading?<div className="following-empty"><span className="spinner"/><p>Carregando armários...</p></div>:sellers.length===0?<div className="following-empty"><Store/><h2>Você ainda não segue armários</h2><p>Visite o perfil de um vendedor e toque em Seguir.</p><a href="/buscar">Explorar catálogo</a></div>:<div className="following-grid">{sellers.map(seller=><article key={seller.id}><a href={`/armario/${seller.id}`}>{seller.avatar_url?<img src={seller.avatar_url} alt="Foto do vendedor"/>:<span>{initials(seller.display_name)}</span>}<div><h2>{seller.display_name}</h2><p><MapPin/> {[seller.city,seller.state].filter(Boolean).join(", ")||"Brasil"}</p><small>{seller.bio||"Peças em movimento no ViraVeste."}</small></div></a><button disabled={working===seller.id} onClick={()=>unfollow(seller.id)}><UserMinus/> Deixar de seguir</button></article>)}</div>}</div></main>;
}
