import { env } from "cloudflare:workers";

type Runtime={baseUrl:string;apiKey:string};
type Row=Record<string,unknown>;
function config():Runtime|null{const runtime=env as unknown as Record<string,string|undefined>;return runtime.SUPABASE_URL&&runtime.SUPABASE_PUBLISHABLE_KEY?{baseUrl:runtime.SUPABASE_URL,apiKey:runtime.SUPABASE_PUBLISHABLE_KEY}:null}
function tokenFor(request:Request){const part=request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith("vv_access_token="));return part?decodeURIComponent(part.slice("vv_access_token=".length)):null}
function headers(apiKey:string,token:string,extra:Record<string,string>={}){return{apikey:apiKey,Authorization:`Bearer ${token}`,...extra}}
async function userId(runtime:Runtime,token:string){const response=await fetch(`${runtime.baseUrl}/auth/v1/user`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return null;return(await response.json() as {id:string}).id}
const valid=(id:string)=>/^[0-9a-f-]{36}$/i.test(id);
async function setup(request:Request){const runtime=config();if(!runtime)return{error:Response.json({error:"Conexão não configurada."},{status:503})};const token=tokenFor(request);if(!token)return{error:Response.json({error:"Entre na sua conta para acessar os pedidos."},{status:401})};const user=await userId(runtime,token);if(!user)return{error:Response.json({error:"Sua sessão expirou."},{status:401})};return{runtime,token,user}}

export async function GET(request:Request){
 const auth=await setup(request);if(auth.error)return auth.error;const {runtime,token,user}=auth;const fields="id,listing_id,offer_id,buyer_id,seller_id,sale_mode,item_price,protection_fee,shipping_price,total_amount,payment_method,payment_status,order_status,shipping_method,tracking_code,created_at,paid_at,shipped_at,delivered_at,completed_at,cancelled_at";const response=await fetch(`${runtime.baseUrl}/rest/v1/orders?select=${fields}&or=(buyer_id.eq.${user},seller_id.eq.${user})&order=created_at.desc`,{headers:headers(runtime.apiKey,token),cache:"no-store"});if(!response.ok)return Response.json({error:"Não foi possível carregar os pedidos."},{status:response.status});const rows=await response.json() as Row[];const orders=await Promise.all(rows.map(async order=>{const listingId=String(order.listing_id),otherId=String(order.buyer_id===user?order.seller_id:order.buyer_id);const [listingResponse,profileResponse]=await Promise.all([fetch(`${runtime.baseUrl}/rest/v1/listings?select=id,title,image_urls,brand,size,dimensions,item_condition&id=eq.${listingId}`,{headers:headers(runtime.apiKey,token),cache:"no-store"}),fetch(`${runtime.baseUrl}/rest/v1/public_seller_profiles?select=id,display_name,avatar_url&id=eq.${otherId}`,{headers:headers(runtime.apiKey,token),cache:"no-store"})]);const listings=listingResponse.ok?await listingResponse.json() as Row[]:[],profiles=profileResponse.ok?await profileResponse.json() as Row[]:[];return{...order,listing:listings[0]||null,other:profiles[0]||null,role:order.buyer_id===user?"buyer":"seller"}}));return Response.json({orders,currentUserId:user});
}

export async function POST(request:Request){
 const auth=await setup(request);if(auth.error)return auth.error;const {runtime,token,user}=auth;const body=await request.json() as {listingId?:string;offerId?:string|null;addressId?:string;shippingMethod?:string;paymentMethod?:string};const listingId=String(body.listingId||""),offerId=body.offerId?String(body.offerId):null,addressId=String(body.addressId||"");if(!valid(listingId)||!valid(addressId)||(offerId&&!valid(offerId)))return Response.json({error:"Confira os dados do pedido."},{status:400});const shippingMethod=body.shippingMethod==="express"?"express":"standard",paymentMethod=body.paymentMethod==="pix"?"pix":"credit_card";
 const [listingResponse,addressResponse]=await Promise.all([fetch(`${runtime.baseUrl}/rest/v1/listings?select=id,seller_id,price,starting_bid,sale_mode,status&id=eq.${listingId}`,{headers:headers(runtime.apiKey,token),cache:"no-store"}),fetch(`${runtime.baseUrl}/rest/v1/addresses?select=id,recipient_name,postal_code,street,number,complement,neighborhood,city,state&id=eq.${addressId}&user_id=eq.${user}`,{headers:headers(runtime.apiKey,token),cache:"no-store"})]);const listings=listingResponse.ok?await listingResponse.json() as Array<{seller_id:string;price:number|null;starting_bid:number|null;sale_mode:string;status:string}>:[],addresses=addressResponse.ok?await addressResponse.json() as Array<Record<string,string|null>>:[];const listing=listings[0],address=addresses[0];if(!listing||listing.status!=="published")return Response.json({error:"O anúncio não está mais disponível."},{status:400});if(listing.seller_id===user)return Response.json({error:"Você não pode comprar seu próprio anúncio."},{status:400});if(!address)return Response.json({error:"Escolha um endereço de entrega válido."},{status:400});
 let itemPrice=Number(listing.price||listing.starting_bid||0),saleMode=listing.sale_mode;if(offerId){const offerResponse=await fetch(`${runtime.baseUrl}/rest/v1/offers?select=id,listing_id,buyer_id,seller_id,created_by,amount,status,expires_at&id=eq.${offerId}`,{headers:headers(runtime.apiKey,token),cache:"no-store"});const offers=offerResponse.ok?await offerResponse.json() as Array<{listing_id:string;buyer_id:string;seller_id:string;created_by:string;amount:number;status:string;expires_at:string}>:[],offer=offers[0];const allowed=offer&&offer.listing_id===listingId&&offer.buyer_id===user&&offer.seller_id===listing.seller_id&&(offer.status==="accepted"||(offer.status==="pending"&&offer.created_by===offer.seller_id&&new Date(offer.expires_at).getTime()>Date.now()));if(!allowed)return Response.json({error:"A proposta não está disponível para esta compra."},{status:400});itemPrice=Number(offer.amount);saleMode="offer"}
 if(!Number.isFinite(itemPrice)||itemPrice<=0)return Response.json({error:"O anúncio não possui um preço válido."},{status:400});const existingResponse=await fetch(`${runtime.baseUrl}/rest/v1/orders?select=id&buyer_id=eq.${user}&listing_id=eq.${listingId}&order_status=not.in.(cancelled,completed)&limit=1`,{headers:headers(runtime.apiKey,token),cache:"no-store"});const existing=existingResponse.ok?await existingResponse.json() as Array<{id:string}>:[];if(existing.length)return Response.json({orderId:existing[0].id,existing:true});const shippingPrice=shippingMethod==="express"?32.5:18.9,protectionFee=Number((itemPrice*.06+.6).toFixed(2)),total=Number((itemPrice+shippingPrice+protectionFee).toFixed(2));const response=await fetch(`${runtime.baseUrl}/rest/v1/orders`,{method:"POST",headers:headers(runtime.apiKey,token,{"content-type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({listing_id:listingId,offer_id:offerId,buyer_id:user,seller_id:listing.seller_id,sale_mode:saleMode,item_price:itemPrice,protection_fee:protectionFee,shipping_price:shippingPrice,total_amount:total,payment_method:paymentMethod,payment_status:"pending",order_status:"awaiting_payment",shipping_method:shippingMethod,recipient_name:address.recipient_name,postal_code:address.postal_code,street:address.street,address_number:address.number,complement:address.complement,neighborhood:address.neighborhood,city:address.city,state:address.state})});if(!response.ok)return Response.json({error:"Não foi possível criar o pedido."},{status:response.status});const rows=await response.json() as Array<{id:string}>;return Response.json({orderId:rows[0].id},{status:201});
}
